# ============================================================
# Dev Environment Configuration (SauceDemo)
# ============================================================
base.url=https://www.saucedemo.com
browser=chrome
headless=false
explicit.wait.timeout=10
thread.count=1
screenshot.on.failure=true
retry.count=1
env=dev
ci.mode=false

# Page URLs
page.url.login=https://www.saucedemo.com
